import { requireCapability } from "@/lib/auth/require-capability";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { findTemplate } from "@/lib/hr-letters/templates";
import { LETTER_TYPE_VALUES, type LetterTypeValue } from "@/lib/hr-letters/letter-type-map";
import Link from "next/link";

// 2026-08-27 — "jis employe ko ye latter issue ho uska record teyar hota
// jaye incase baad me chaek kare to vaha par mil jaye ... record kese
// dikhega, kaha par mantain hoyega sab dikhe": this IS that record — every
// letter issued via the new "📌 Save Record & Assign Dispatch No." button
// on the letter form (letter-form.tsx) lands here, searchable/filterable,
// with a link through to re-view/reprint/re-export it later. Direct
// equivalent of the old Google-Sheets "Letter Log" sheet (SR NO / DATE /
// COMPANY / EMPLOYEE NAME / EMPLOYEE CODE / LETTER TYPE / REF NO. /
// GENERATED BY / GENERATED ON), now backed by hr_letters instead of a
// LockService-guarded counter sheet.
//
// Plain GET <form> for the filters (below) — no client JS needed, the
// filter values just become the page's own searchParams, so this whole
// page stays a Server Component and every filtered query runs server-side
// against the (potentially large, over time) hr_letters table instead of
// shipping every row to the browser and filtering client-side.
//
// service-role client — hr_letters has RLS enabled+forced with no
// policies (confirmed live 2026-08-27), same as every other newer table in
// this codebase; requireCapability("hr_letters") below is what actually
// gates access here.
export default async function HrLettersRecordsPage({
  searchParams,
}: {
  searchParams: Promise<{ company?: string; employee?: string; type?: string; q?: string; from?: string; to?: string }>;
}) {
  const authed = await requireCapability("hr_letters");
  const sp = await searchParams;

  const db = createServiceRoleClient();

  let query = db
    .from("hr_letters")
    .select(
      "id, ref_no, letter_type, template_slug, for_employee_id, for_employee_name_snapshot, for_employee_code_snapshot, for_company_id, letter_date, generated_by_employee_id, generated_on"
    )
    .in("for_company_id", authed.companyIds)
    .order("generated_on", { ascending: false })
    .limit(500);

  if (sp.company) query = query.eq("for_company_id", sp.company);
  if (sp.employee) query = query.eq("for_employee_id", sp.employee);
  if (sp.type && (LETTER_TYPE_VALUES as string[]).includes(sp.type)) {
    query = query.eq("letter_type", sp.type as LetterTypeValue);
  }
  if (sp.from) query = query.gte("letter_date", sp.from);
  if (sp.to) query = query.lte("letter_date", sp.to);
  if (sp.q) {
    const q = sp.q.replace(/[%,]/g, "");
    if (q) query = query.or(`for_employee_name_snapshot.ilike.%${q}%,ref_no.ilike.%${q}%,for_employee_code_snapshot.ilike.%${q}%`);
  }

  const [{ data: rows }, { data: companies }, { data: employeesById }] = await Promise.all([
    query,
    db.from("companies").select("id, name").in("id", authed.companyIds).order("name"),
    db.from("employees").select("id, name"),
  ]);

  const nameById = new Map((employeesById ?? []).map((e) => [e.id, e.name]));
  const companyById = new Map((companies ?? []).map((c) => [c.id, c.name]));

  const inputClass =
    "w-full rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 text-xs text-slate-900 outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500";

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-slate-900">📋 Issued Letters Record</h1>
          <p className="mt-1 text-sm text-slate-500">
            Every HR letter issued from this system, with its dispatch no. — search, filter, and reopen any past
            letter to view, reprint, or re-export it.
          </p>
        </div>
        <Link
          href="/dashboard/hr-letters"
          className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50"
        >
          ← Back to HR Letters
        </Link>
      </div>

      <form method="GET" className="mb-4 grid grid-cols-2 gap-3 rounded-xl border border-slate-200 bg-white p-4 md:grid-cols-6">
        <div>
          <label className="mb-1 block text-xs font-medium text-slate-500">Search</label>
          <input name="q" defaultValue={sp.q ?? ""} placeholder="Name, code, or dispatch no." className={inputClass} />
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-slate-500">Company</label>
          <select name="company" defaultValue={sp.company ?? ""} className={inputClass}>
            <option value="">All companies</option>
            {(companies ?? []).map((c) => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-slate-500">Letter Type</label>
          <select name="type" defaultValue={sp.type ?? ""} className={inputClass}>
            <option value="">All types</option>
            {LETTER_TYPE_VALUES.map((t) => (
              <option key={t} value={t}>{t}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-slate-500">From</label>
          <input type="date" name="from" defaultValue={sp.from ?? ""} className={inputClass} />
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-slate-500">To</label>
          <input type="date" name="to" defaultValue={sp.to ?? ""} className={inputClass} />
        </div>
        <div className="flex items-end gap-2">
          <button type="submit" className="w-full rounded-lg bg-amber-500 px-3 py-1.5 text-xs font-semibold text-white hover:bg-amber-600">
            Filter
          </button>
          {(sp.q || sp.company || sp.employee || sp.type || sp.from || sp.to) && (
            <Link
              href="/dashboard/hr-letters/records"
              className="w-full rounded-lg border border-slate-300 px-3 py-1.5 text-center text-xs font-medium text-slate-600 hover:bg-slate-50"
            >
              Clear
            </Link>
          )}
        </div>
      </form>

      <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-slate-200 text-slate-400">
              <th className="px-3 py-2">Dispatch No.</th>
              <th className="px-3 py-2">Date</th>
              <th className="px-3 py-2">Company</th>
              <th className="px-3 py-2">Employee</th>
              <th className="px-3 py-2">Emp. Code</th>
              <th className="px-3 py-2">Letter Type</th>
              <th className="px-3 py-2">Generated By</th>
              <th className="px-3 py-2">Generated On</th>
              <th className="px-3 py-2"></th>
            </tr>
          </thead>
          <tbody>
            {(rows ?? []).map((r) => {
              const template = r.template_slug ? findTemplate(r.template_slug) : undefined;
              return (
                <tr key={r.id} className="border-t border-slate-100">
                  <td className="px-3 py-2 font-mono font-medium text-slate-800">{r.ref_no ?? "—"}</td>
                  <td className="px-3 py-2 text-slate-500">{r.letter_date}</td>
                  <td className="px-3 py-2 text-slate-600">{companyById.get(r.for_company_id) ?? "—"}</td>
                  <td className="px-3 py-2 text-slate-800">{r.for_employee_name_snapshot}</td>
                  <td className="px-3 py-2 text-slate-500">{r.for_employee_code_snapshot ?? "—"}</td>
                  <td className="px-3 py-2 text-slate-600">
                    {template ? `${template.icon} ${template.title}` : r.letter_type}
                  </td>
                  <td className="px-3 py-2 text-slate-500">{nameById.get(r.generated_by_employee_id) ?? "—"}</td>
                  <td className="px-3 py-2 text-slate-400">{new Date(r.generated_on).toLocaleString("en-IN")}</td>
                  <td className="px-3 py-2">
                    <Link href={`/dashboard/hr-letters/records/${r.id}`} className="font-medium text-amber-600 hover:underline">
                      View / Reprint →
                    </Link>
                  </td>
                </tr>
              );
            })}
            {(rows ?? []).length === 0 && (
              <tr>
                <td colSpan={9} className="px-3 py-6 text-center text-slate-400">
                  No letters issued yet — issue one from any HR Letter template and it will appear here with its
                  dispatch no.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
