-- =====================================================================
-- Shipglobal shipment creation + label generation (2026-08-10).
--
-- User provided Shipglobal's own REST API docs directly (customers.php
-- login, addOrder.php shipment creation, processDestination.php
-- manifest-and-get-tracking-number) and asked for the FULL flow — not
-- just tracking, actual shipment creation — unlike every other courier in
-- this app (Delhivery/UPS/FedEx/Aramex/Shiprocket), which only react to an
-- AWB that was already generated by hand outside this app.
--
-- SCHEMA GAP THIS MIGRATION FILLS: neither `orders` nor `dispatch_invoices`
-- store a STRUCTURED shipping address (orders.buyer_name_address is one
-- free-text blob; dispatch_invoices has buyer_name/buyer_mail/
-- buyer_contact/buyer_country but no address lines/city/postcode/state).
-- Shipglobal's addOrder.php requires exact structured fields (country_code,
-- postcode, city, state all separately) for real customs-bound
-- international shipments — parsing these out of free text would risk
-- real shipping failures, so shipglobal_shipments below captures them
-- fresh via a dedicated form instead of trying to derive them.
--
-- Similarly, `company_profiles` (the existing "invoicing/bank block", see
-- db/schema.sql) has a single free-text `address` and no first/last name,
-- city/postcode/state/country_code split, or tax_id_type — not structured
-- enough for Shipglobal's seller_* fields either, and it's a DIFFERENT
-- concern (invoicing vs. cross-border shipping declarations) per that
-- table's own header comment about staying narrowly scoped. Hence a new
-- shipglobal_seller_profiles table (one row per company, filled in once
-- via an admin form) rather than extending company_profiles.
--
-- Run this AFTER db/2026-08-08-enable-rls.sql, then RE-RUN
-- db/2026-08-08-enable-rls.sql once more so its authenticated-only policy
-- picks up these 2 new tables too (same instruction as every other dated
-- migration here — that script loops over every table in `public` at run
-- time, so a second pass is needed for tables that didn't exist on the
-- first pass).
-- =====================================================================

-- One row per company (Nyko Mart / Rugara / CASA ARRA) — the "who is
-- shipping this" declaration Shipglobal requires on every addOrder.php
-- call. Filled in once via an admin settings form, not per-shipment.
CREATE TABLE shipglobal_seller_profiles (
  company_id        uuid PRIMARY KEY REFERENCES companies(id) ON DELETE CASCADE,
  seller_nickname   text NOT NULL,
  seller_firstname  text NOT NULL,
  seller_lastname   text NOT NULL,
  seller_mobile     text NOT NULL,
  seller_email      text NOT NULL,
  seller_company    text NOT NULL,
  seller_address1   text NOT NULL,
  seller_address2   text NOT NULL,
  seller_address3   text,
  seller_city       text NOT NULL,
  seller_postcode   text NOT NULL,
  seller_country_code text NOT NULL,   -- 2-letter ISO, e.g. 'IN'
  seller_state      text NOT NULL,
  seller_tax_id_type text,             -- e.g. 'GSTIN' — optional per Shipglobal's docs
  seller_tax_id     text,              -- could default from company_profiles.gstin at entry time, but kept separate/explicit here
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- One row per Shipglobal shipment attempt, 1:1 with an order. Two-phase
-- per Shipglobal's own API shape: addOrder.php ("created", gets a label +
-- waybill_number) then processDestination.php ("manifested", gets the
-- REAL carrier tracking_no) — status tracks which phase this row is at.
-- Every request/response is logged in full (raw_create_response /
-- raw_manifest_response), same "never silently lose data" philosophy as
-- courier_webhook_log.
CREATE TABLE shipglobal_shipments (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id              uuid NOT NULL UNIQUE REFERENCES orders(id),

  service_code          text NOT NULL,   -- 'DPD-CLASSIC' | 'UNIUNI-CLASSIC' | 'VIPPARCEL-CLASSIC' | 'DHLECS-CLASSIC' | 'UBI-CLASSIC'
  currency_code          text NOT NULL DEFAULT 'USD',
  csb5_status             smallint NOT NULL DEFAULT 1,

  -- Structured buyer shipping address — see header comment on why this
  -- can't be derived from orders.buyer_name_address.
  ship_firstname          text NOT NULL,
  ship_lastname           text NOT NULL,
  ship_mobile             text NOT NULL,
  ship_email              text NOT NULL,
  ship_company            text,
  ship_address1           text NOT NULL,
  ship_address2           text NOT NULL,
  ship_address3           text,
  ship_city                text NOT NULL,
  ship_postcode            text NOT NULL,
  ship_country_code        text NOT NULL,   -- 2-letter ISO
  ship_state                text NOT NULL,

  -- Single line item — matches this app's existing convention of one
  -- SKU/qty per `orders` row (see db/schema.sql SECTION on orders).
  item_name                 text NOT NULL,
  item_sku                  text NOT NULL,
  item_qty                  integer NOT NULL DEFAULT 1,
  item_unit_price            numeric(12,2) NOT NULL,
  item_hsn                   text NOT NULL,
  item_tax_rate               numeric(5,2) NOT NULL DEFAULT 0,

  package_weight_g              integer NOT NULL,   -- grams, per Shipglobal's field-units reference
  package_length_cm              integer NOT NULL,
  package_breadth_cm              integer NOT NULL,
  package_height_cm                integer NOT NULL,

  ioss_number                       text,           -- optional; UI prefills from orders.tax_id if present
  seller_reference                   text NOT NULL,  -- addOrder.php's required "tracking" field — a SELLER-assigned reference, not the real courier tracking number (that comes from processDestination.php below)
  mail_class                          text,           -- optional (mandatory only for VIPPARCEL — enforced in application code, not here)
  delivery_confirmation                 text,

  manifest_code                          text,        -- set at manifest time (processDestination.php)

  status                                  text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','created','manifested','failed')),
  shipglobal_order_number                  text,       -- addOrder.php response: data.order_number
  shipglobal_waybill_number                 text,      -- addOrder.php response: data.waybill_number
  tracking_no                                text,      -- processDestination.php response: data[].trackingNo — the REAL courier tracking number
  label_pdf_base64                            text,      -- addOrder.php response: data.pdf_base64, served via /api/shipglobal-label/[id]
  error_message                                text,

  raw_create_response                           jsonb,
  raw_manifest_response                          jsonb,

  created_at                                      timestamptz NOT NULL DEFAULT now(),
  created_by                                       uuid REFERENCES employees(id)
);
CREATE INDEX idx_shipglobal_shipments_order ON shipglobal_shipments(order_id);
CREATE INDEX idx_shipglobal_shipments_tracking ON shipglobal_shipments(tracking_no);

-- New tables need RLS too — see header comment. Enabling here as a
-- baseline; the authenticated-all policy gets attached when
-- 2026-08-08-enable-rls.sql is re-run after this file.
ALTER TABLE shipglobal_seller_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipglobal_shipments ENABLE ROW LEVEL SECURITY;

-- New capability, deliberately NOT granted to the general 'Order Entry'
-- role by default — this action creates a REAL external shipment (costs
-- money, generates a real customs declaration) the moment real Shipglobal
-- credentials are live, so it starts scoped to Admin/MD only. Grant it to
-- more roles via Admin > Permissions in the app if that's too narrow.
INSERT INTO capabilities (code, description) VALUES
  ('shipglobal_shipment', 'Create Shipglobal shipments (real external shipment + label + customs declaration)');

INSERT INTO role_capabilities (role_id, capability_code)
SELECT r.id, 'shipglobal_shipment' FROM roles r WHERE r.name IN ('Admin', 'MD');
