"use server";

// Cancel Shipment (EGS-integration round, 2026-09-04 — EGS's own Shipment
// History Detail page has this exact modal: reason dropdown + remark).
// Marks the courier_shipments row 'cancelled' (see
// db/2026-09-04-egs-integration-pickup-and-cancel.sql for the widened
// CHECK constraint + new columns) and flips the order back off "Shipped".
//
// HONEST SCOPE: this does NOT call any courier's real cancel-shipment API
// — none of the 6 couriers' cancel/void endpoints have been researched or
// verified (same "never fake an unverified API call" standard as Pickup
// Request — see that feature's own actions file). This records that the
// shipment was cancelled on OUR side; staff still need to cancel/void the
// AWB with the courier directly if it was already manifested with them.
//
// 2026-09-04 — auto-invoice teardown. If a booking auto-generated a CSB-V
// sales invoice (see courier-booking/actions.ts's
// maybeAutoGenerateCsbVInvoiceForBooking), cancelling that shipment must not
// leave the invoice + its reserved invoice number orphaned. Reuses
// deleteInvoiceCore() (invoices/actions.ts) — the EXACT unlink-then-delete
// logic deleteInvoice()'s own capability-gated wrapper calls — WITHOUT
// re-checking the `invoicing` capability a second time: this action is
// already authorized via `courier_booking_shipment` + the company check
// below, and a member of staff without `invoicing` access must still be
// able to cancel a shipment; the invoice cleanup is a side effect of that,
// not a second invoicing action of their own.
//
// KNOWN LIMITATION, stated plainly rather than silently assumed away:
// sales_invoices has no column linking an invoice back to the specific
// order_shipment/courier_shipments row that caused it — orders.invoice_id
// is a single slot per order, not per shipment attempt. So this cannot
// distinguish "this invoice was auto-generated by the shipment just
// cancelled" from "this order already had some other invoice (manual, or
// from an earlier still-active shipment) before this cancellation" — it
// deletes WHATEVER invoice the order currently has, same as the literal
// scope handed down for this round. In practice this is safe for the
// common case (one shipment, one auto-invoice, cancel undoes both), but a
// re-booking/multi-shipment order could have this teardown remove an
// invoice unrelated to the shipment being cancelled. Flagged here and in
// the round's own report rather than inventing a new schema column to
// fully solve it without stopping to ask first, per this project's
// standing DB-migration rule.
import { requireCapability } from "@/lib/auth/require-capability";
import { createServiceRoleClient } from "@/lib/supabase/server";
import { deleteInvoiceCore } from "@/app/dashboard/invoices/actions";
import { revalidatePath } from "next/cache";

function str(formData: FormData, key: string): string {
  return String(formData.get(key) ?? "").trim();
}
function strOrNull(formData: FormData, key: string): string | null {
  const v = str(formData, key);
  return v ? v : null;
}

export type CancelShipmentState = { error: string | null; success: boolean };
const INITIAL: CancelShipmentState = { error: null, success: false };

export async function cancelShipment(_prev: CancelShipmentState, formData: FormData): Promise<CancelShipmentState> {
  const employee = await requireCapability("courier_booking_shipment");
  const supabase = createServiceRoleClient();

  const courierShipmentId = str(formData, "courier_shipment_id");
  const reason = str(formData, "cancel_reason");
  if (!courierShipmentId) return { ...INITIAL, error: "Missing shipment." };
  if (!reason) return { ...INITIAL, error: "Pick a cancellation reason." };

  const { data: shipment } = await supabase.from("courier_shipments").select("id, order_id").eq("id", courierShipmentId).maybeSingle();
  if (!shipment) return { ...INITIAL, error: "Shipment not found." };

  const { data: order } = await supabase.from("orders").select("id, invoice_id").eq("id", shipment.order_id).in("company_id", employee.companyIds).maybeSingle();
  if (!order) return { ...INITIAL, error: "Not authorized for this shipment's company." };

  const { error } = await supabase
    .from("courier_shipments")
    .update({
      status: "cancelled",
      cancel_reason: reason,
      cancel_remark: strOrNull(formData, "cancel_remark"),
      cancelled_at: new Date().toISOString(),
    })
    .eq("id", courierShipmentId);
  if (error) return { ...INITIAL, error: error.message };

  // Order was flagged 'Shipped' at booking time (writeOrderShipmentFromBooking
  // in ../actions.ts) — cancelling the shipment reverts that so it shows
  // back up in Pending Orders / doesn't read as in-flight.
  await supabase.from("orders").update({ shipment_status: "Cancelled" }).eq("id", shipment.order_id);

  // Auto-invoice teardown — see this file's header comment.
  if (order.invoice_id) {
    const teardown = await deleteInvoiceCore(supabase, order.invoice_id);
    if (teardown.error) {
      console.error(`[auto-invoice] failed to delete invoice ${order.invoice_id} after cancelling shipment ${courierShipmentId}: ${teardown.error}`);
    }
  }

  revalidatePath("/dashboard/courier-booking");
  revalidatePath(`/dashboard/courier-booking/shipment/${courierShipmentId}`);
  return { error: null, success: true };
}
